project_name: test
description: "hello world"

triggers:
  - name: build_new_commit
    url: "https://github.com/fluidic/beaver_demo"
    type: github
    events: ["push"]
    task:
      - name: git
        args: ["clone", "trigger:url"]
      - name: pub
        args: ["--process-working-dir", "beaver_demo", "get"]
      - name: pub
        args: ["--process-working-dir", "beaver_demo", "run", "test"]
      - name: mail
        args: ["dev@fluidic.io"]
  - name: daily_build
    type: cron
    task:
      - name: trigger
        args: ["build_master"]
      - name: mail
        args: ["dev@fluidic.io"]
  - name: build_master
    type: internal
    task:
      - name: git
        args: ["clone", "https://github.com/fluidic/beaver_demo"]
      - name: pub
        args: ["--process-working-dir", "beaver_demo", "get"]
      - name: pub
        args: ["--process-working-dir", "beaver_demo", "run", "test"]
      - name: mail
        args: ["dev@fluidic.io"]