project_name: test
description: "hello world"

triggers:
  - name: build_new_commit
    url: "https://github.com/fluidic/beaver_demo"
    type: github
    events: ["push"]
    task:
      - name: git
        args: ["clone", "trigger:url"]
      - name: pub
        args: ["--process-working-dir", "beaver_demo", "get"]
      - name: pub
        args: ["--process-working-dir", "beaver_demo", "run", "test"]
      - name: mail
        args: ["dev@fluidic.io"]
  - name: daily_build
    type: cron
    task:
      - name: download
        args: ["https://raw.githubusercontent.com/fluidic/beaver/master/beaver_trigger_handler/README.md", "."]
